routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// -- Authentication Routes
Auth::routes();

// -- BEGIN -- public routes
Route::get('/', function () {
    return view('welcome');
});

Route::get('logout', function () {
    Auth::logout();
    session()->flush();
    return redirect('/');
});

Route::get('home', function () {
    return redirect()->route('dashboard.index');
});
// -- END -- Public routes

// -- BEGIN -- Model binding
    Route::model('activitylog', App\ActivityLog::class);
// -- END -- Model binding

// -- BEGIN -- Private route
Route::middleware('auth')->group(function () {
    // -- BEGIN -- Resource route
    Route::resource('dashboard', 'DashboardController', ['only' => ['index']]);
    Route::middleware('RoleAuth:App\User')
        ->resource('users', 'UsersController', ['except' => ['show']]);
    Route::middleware('RoleAuth:App\Module')
        ->resource('modules', 'ModulesController');
    Route::middleware('RoleAuth:App\Staff')
        ->resource('staffs', 'StaffsController');
    Route::middleware('RoleAuth:App\Rolegroup')
        ->resource('rolegroups', 'RolegroupsController', ['except' => ['show']]);
    Route::middleware('RoleAuth:App\Event')
        ->resource('events', 'EventsController');
    Route::middleware('RoleAuth:App\Activity')
        ->resource('activities', 'ActivitiesController');
    Route::middleware('RoleAuth:App\ActivityLog')
        ->resource('activitylogs', 'ActivityLogsController');
    Route::middleware('RoleAuth:App\Institute')
        ->resource('institutes', 'InstitutesController');
    Route::middleware('RoleAuth:App\Department')
        ->resource('departments', 'DepartmentsController');
    Route::middleware('RoleAuth:App\Calendar')
        ->resource('calendar', 'CalendarController');
    // -- END -- Resource binding

    // -- BEGIN -- Datatables Specific
    Route::group(['prefix' => 'datatables'], function () {
        Route::post('users', 'DatatablesController@users')
            ->name('datatables.users');
        Route::post('rolegroups', 'DatatablesController@rolegroups')
            ->name('datatables.rolegroups');
        Route::post('modules', 'DatatablesController@modules')
            ->name('datatables.modules');
        Route::post('activities', 'DatatablesController@activities')
            ->name('datatables.activities');
        // Route::post('staffs', 'StaffsController@getDatatablesResources')
        //     ->name('staffs.datatables');
        // Route::post('rolegroups', 'RolegroupsController@getDatatablesResources')
        //     ->name('rolegroups.datatables');
        // Route::post('institutes', 'InstitutesController@getDatatablesResources')
        //     ->name('institutes.datatables');
        // Route::post('departments', 'DepartmentsController@getDatatablesResources')
        //     ->name('departments.datatables');
    });
    // -- END -- Datatables Specific

    // -- BEGIN -- Other API Router
    Route::post('rolegroups/add_modules/{id}', 'RolegroupsController@addModules')
        ->name('rolegroups.addModules');
    Route::post('rolegroups/remove_modules/{id}', 'RolegroupsController@removeModules')
        ->name('rolegroups.removeModules');
    // -- END -- Other API Router
});
// -- END -- Model binding

app/Institute.php
<?php

namespace App;

use App\BaseModel as Model;

class Institute extends Model
{
    /**
     * Fillable column
     *
     * @var array
     */
    protected $fillable = [
        'title', 'name', 'type'
    ];

    /**
     * Appended column
     *
     * @var array
     */
    protected $appends = [
        'full_title'
    ];

    /**
     * Type id for every institutes in one periode
     * @var [type]
     */
    private static $types = [
        '1' => 'eksekutif',
        '2' => 'legislatif',
        '3' => 'yudikatif',
    ];

    /**
     * Make cooked types with [id] => 'type'
     *
     * @return array of types
     */
    public static function getCookedTypes()
    {
        $types = [];
        foreach (static::$types as $id => $type) {
            $types[$id] = "Lembaga ".ucfirst($type);
        }

        return $types;
    }

    /**
     * Get specific types based on id
     *
     * @param  integer $type_id type id
     * @return string        type
     */
    public static function getType($type_id)
    {
        return static::$types[$type_id];
    }

    /**
     * Attribute to show Intiials + cabinet name
     *
     * @return string
     */
    public function getFullTitleAttribute()
    {
        return getInitials($this->title)." ".$this->name;
    }

    /**
     * One-to-many relation to department
     *
     * @return \App\Department instance of department
     */
    public function departments()
    {
        return $this->hasMany('App\Department');
    }
}

app/Http/Controllers/InstitutesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Institute;
use App\Http\Requests\UpdateInstituteRequest;

use Datatables;
use DB;
use Flash;

class InstitutesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $institutes = Institute::with('departments')->orderBy('type')->get();
        return view('institutes.index')->with('institutes', $institutes);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('institutes.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UpdateInstituteRequest $request)
    {
        $institute = DB::transaction(function () use ($request) {
            $institute = Institute::create($request->all());

            // TODO : Lock core
            $institute->departments()->create([
                'title' => 'core',
                'alias' => 'core',
                'description' => 'core',
                'vision' => 'core',
                'mission' => 'core',
            ]);

            return $institute;
        });
        return redirect()->route('institutes.show', $institute->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Institute  $institute
     * @return \Illuminate\Http\Response
     */
    public function show(Institute $institute)
    {
        return view('institutes.show')->with(['institute' => $institute]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Institute  $institute
     * @return \Illuminate\Http\Response
     */
    public function edit(Institute $institute)
    {
        return view('institutes.form')->with(['institute' => $institute]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests  $request
     * @param  \App\Institute  $institute
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateInstituteRequest $request, Institute $institute)
    {
        $institute = DB::transaction(function () use ($request, $institute) {
            $institute->update($request->all());
            return $institute;
        });
        return redirect()->route('institutes.show', $institute->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Institute  $institute
     * @return \Illuminate\Http\Response
     */
    public function destroy(Institute $institute)
    {
        DB::transaction(function () use ($institute) {
            $institute->delete();
        });
        return redirect()->route('institutes.index');
    }

    // -- BEGIN -- Custom Function

    /**
     * AJAX datatables resources handler
     *
     * @return JSON Datatable Ready JSON
     */
    public function getDatatablesResources()
    {
        if (\App\Helper\AuthHelper::isXUser('READ', 'institutes')) {
            $institutes = new Institute();
        } else {
            $institutes = Institute::where('rolegroup_depth', '>', '0');
        }

        return Datatables::of($institutes->with(['departments', 'departments.members'])->get([
            'id', 'title', 'name'
            ]))
            ->addColumn('members', function ($institute) {
                $members = 0;
                $institute->departments->each(function ($department) use (&$members) {
                    $members += $department->members()->count();
                });
                return $members;
            })
            ->addColumn('action', function ($institute) {
                $settings = [
                    'title' => 'institutes',
                    'module' => $institute,
                    'part' => [
                        'view' => $this->authorize('view', $institute),
                        'edit' => $this->authorize('edit', $institute),
                        'delete' => $this->authorize('delete', $institute),
                    ]
                ];
                $html = view('layouts.datatablesActionColumn')->with($settings)->render();
                return $html;
            })
            ->removeColumn('id')
            ->make(true);
    }
}

resources/views/institutes/form.blade.php
@extends('layouts.dashboard')

@section('css')
@endsection

@section('breadcrumbs')
{!! Layouts::breadcrumbs(['type' => $isEdit ? 'edit' : 'create', 'module' => $isEdit ? $institute : null, 'route' => 'institutes'], true) !!}
@endsection

@section('content')
<section class="content">
    <h4>{{ $isEdit ? "EDIT" : "CREATE NEW" }} <span class="text-uppercase">@choice('institutes.title', 1)</span></h4>
    <div class="row">
        <div class="col-xs-12">
            @if ($isEdit)
                {!! Form::model($institute, ['route' => ['institutes.update', $institute->id], 'method' => 'put']) !!}
                {!! Form::hidden('isEdit', true) !!}
            @else
                {!! Form::open(['route' => ['institutes.store'], 'method' => 'post']) !!}
            @endif
            <div class=x_panel>
                <div class=x_title>
                    <strong>@choice('institutes.title', 1) Properties</strong>
                    <small>Form</small>
                </div>
                <div class=x_content>
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="form-group">
                                {!! Form::label('', 'Institute Type', ['class' => 'form-label']) !!}
                                {!! Form::select('type', \App\Institute::getCookedTypes(), null, ['class' => 'form-control select2', $isEdit ? 'disabled' : '']) !!}
                            </div>
                            <div class="form-group">
                                {!! Form::label('', 'Institute Title', ['class' => 'form-label']) !!}
                                {!! Form::text('title', null, ['class' => 'form-control', 'placeholder' => "Badan Eksekutif"]) !!}
                            </div>
                            <div class="form-group">
                                {!! Form::label('', "Institute Name (Cabinet Name)", ['class' => 'form-label']) !!}
                                {!! Form::text('name', null, ['class' => 'form-control']) !!}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-dot-circle-o"></i> Submit</button>
                    <button type="reset" class="btn btn-sm btn-danger"><i class="fa fa-ban"></i> Reset</button>
                    @if ($isEdit)
                        <a href="{{ route('institutes.show', $institute->id) }}" type="button" class="btn btn-sm btn-secondary"><i class="fa fa-arrow-left"></i> Back</a>
                    @endif
                </div>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
</section>
@endsection

@section('js')
@endsection

resources/views/institutes/index.blade.php
@extends('layouts.dashboard')

@section('breadcrumbs')

@endsection

@section('content')
    <div class="page-title">
        <div class="title_left">
            <h3>@choice('institutes'.'.title', 2) <small>(click to view)</small></h3>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
        @foreach ($institutes as $institute)
        <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
            <a href="{{ route('institutes.show', $institute->id) }}">
                <div class="tile-stats">
                    @php
                        switch ($institute->type) {
                            case '1':
                                $icon = 'fa-users';
                                break;
                            case '2':
                                $icon = 'fa-file-text-o';
                                break;
                            case '3':
                                $icon = 'fa-university';
                                break;

                            default:
                                $icon = 'fa-sitemap';
                                break;
                        }
                    @endphp
                    <div class="icon"><i class="fa {{ $icon }}"></i>
                    </div>
                    <div class="count">{{ $institute->departments->count() }} <span class="small-tile-stats-font">dept</span></div>

                    <h3>{{ $institute->full_title }}</h3>
                    <p>Lorem ipsum psdea itgum rixt.</p>
                </div>
            </a>
        </div>
        @endforeach
        <div class="animated flipInY col-lg-2 col-md-2 col-sm-6 col-xs-12">
            <a href="{{ route('institutes.create') }}">
                <div class="tile">
                    <div class="icon"><i class="fa fa-plus"></i>
                    </div>
                </div>
            </a>
        </div>
    </div>
@stop

resources/views/institutes/show.blade.php
@extends('layouts.dashboard')

@section('css')
@endsection

@section('breadcrumbs')
    <li class="breadcrumb-item"><a href="{{ route('institutes.index') }}">Institute</a></li>
    <li class="breadcrumb-item"><a href="{{ route('institutes.show', $institute->id) }}">{{ getInitials($institute->title)." ".$institute->name }}</a></li>
@endsection

@section('content')
<style type="text/css">
    .dept_profile {
        margin: auto;
        width: 100px;
        height: 100px;
    }
    .dept_name {
        text-align: center;
    }

    p {
        overflow: auto;
    }

    .count {
        text-align: center
    }
</style>
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class=x_panel>
                <div class=x_content>
                    <div class="row">
                        <div class="col-xs-10">
                            <p class="m-b-xs">Lembaga {{ ucfirst(\App\Institute::getType($institute->type)) }}</p>
                            <h3><span class="text-uppercase">{{ $institute->name }}</span> <small>({{ ucwords($institute->title) }})</small></h3>
                        </div>
                        <div class="col-xs-2">
                        @if (auth()->user()->can('update', $institute) or auth()->user()->can('delete', $institute))
                            {!! Form::open(['url' => route('institutes.destroy', $institute->id), 'method'=>'delete' ,]) !!}
                                @can('update', $institute)
                                    <a href="{{ route('institutes.edit', $institute->id) }}" class="btn btn-block btn-primary"><i class="fa fa-fw fa-edit"></i> Edit</a>
                                @endcan
                                @can('delete', $institute)
                                    <a href="#" class="btn btn-block btn-danger js-delete-confirm"><i class="fa fa-fw fa-trash"></i> Delete</a>
                                @endcan
                            {!! Form::close() !!}
                        @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        @foreach ($institute->departments as $department)
            <div class="col-md-3 col-xs-12 widget widget_tally_box">
                <div class="x_panel">
                    <div class="x_content">
                        @if ($department->profile_img !== null)
                            <div class="dept_profile">
                                <img src="{{ asset('images/user.png') }}" alt="..." class="img-circle profile_img">
                            </div>
                        @endif
                        <h3 class="dept_name">{{ $department->alias }}</h3>
                        <div class="row">
                            <div class="col-xs-12 text-center">
                                @can('view', $department)
                                    <a class="btn btn-dark btn-xs" href="{{ route('departments.show', $department->id) }}"><i class="fa fa-eye"></i> View </a>
                                @endcan
                                @can('update', $department)
                                    <a class="btn btn-primary btn-xs" href="{{ route('departments.edit', $department->id) }}"><i class="fa fa-edit"></i> Edit </a>
                                @endcan
                            </div>
                        </div>
                        <div class="line"></div>
                        <div class="row">
                            <div class="col-xs-6 count">
                                <h3>{{ $department->members->count() }}</h3>
                                <span>Members</span>
                            </div>
                            <div class="col-xs-6 count">
                                <h3>1234</h3>
                                <span>Programs</span>
                            </div>
                        </div>
                        <div class="line"></div>
                        <div class="row">
                            <div class="col-xs-12">
                                <p>
                                    {{ $department->description }}
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        @endforeach
        <div class="animated flipInY col-lg-2 col-md-2 col-sm-6 col-xs-12">
            <a href="{{ route('departments.create', ['institute_id' => $institute->id]) }}">
                <div class="tile">
                    <div class="icon"><i class="fa fa-plus"></i>
                    </div>
                </div>
            </a>
        </div>
    </div>
</section>
@endsection

@push('js')
@endpush