routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// -- Authentication Routes
Auth::routes();

// -- BEGIN -- public routes
Route::get('/', function () {
    return view('welcome');
});

Route::get('logout', function () {
    Auth::logout();
    session()->flush();
    return redirect('/');
});

Route::get('home', function () {
    return redirect()->route('dashboard.index');
});
// -- END -- Public routes

// -- BEGIN -- Model binding
    Route::model('activitylog', App\ActivityLog::class);
// -- END -- Model binding

// -- BEGIN -- Private route
Route::middleware('auth')->group(function () {
    // -- BEGIN -- Resource route
    Route::resource('dashboard', 'DashboardController', ['only' => ['index']]);
    Route::middleware('RoleAuth:App\User')
        ->resource('users', 'UsersController', ['except' => ['show']]);
    Route::middleware('RoleAuth:App\Module')
        ->resource('modules', 'ModulesController');
    Route::middleware('RoleAuth:App\Staff')
        ->resource('staffs', 'StaffsController');
    Route::middleware('RoleAuth:App\Rolegroup')
        ->resource('rolegroups', 'RolegroupsController', ['except' => ['show']]);
    Route::middleware('RoleAuth:App\Event')
        ->resource('events', 'EventsController');
    Route::middleware('RoleAuth:App\Activity')
        ->resource('activities', 'ActivitiesController');
    Route::middleware('RoleAuth:App\ActivityLog')
        ->resource('activitylogs', 'ActivityLogsController');
    Route::middleware('RoleAuth:App\Institute')
        ->resource('institutes', 'InstitutesController');
    Route::middleware('RoleAuth:App\Department')
        ->resource('departments', 'DepartmentsController');
    Route::middleware('RoleAuth:App\Calendar')
        ->resource('calendar', 'CalendarController');
    // -- END -- Resource binding

    // -- BEGIN -- Datatables Specific
    Route::group(['prefix' => 'datatables'], function () {
        Route::post('users', 'DatatablesController@users')
            ->name('datatables.users');
        Route::post('rolegroups', 'DatatablesController@rolegroups')
            ->name('datatables.rolegroups');
        Route::post('modules', 'DatatablesController@modules')
            ->name('datatables.modules');
        Route::post('activities', 'DatatablesController@activities')
            ->name('datatables.activities');
        // Route::post('staffs', 'StaffsController@getDatatablesResources')
        //     ->name('staffs.datatables');
        // Route::post('rolegroups', 'RolegroupsController@getDatatablesResources')
        //     ->name('rolegroups.datatables');
        // Route::post('institutes', 'InstitutesController@getDatatablesResources')
        //     ->name('institutes.datatables');
        // Route::post('departments', 'DepartmentsController@getDatatablesResources')
        //     ->name('departments.datatables');
    });
    // -- END -- Datatables Specific

    // -- BEGIN -- Other API Router
    Route::post('rolegroups/add_modules/{id}', 'RolegroupsController@addModules')
        ->name('rolegroups.addModules');
    Route::post('rolegroups/remove_modules/{id}', 'RolegroupsController@removeModules')
        ->name('rolegroups.removeModules');
    // -- END -- Other API Router
});
// -- END -- Model binding

app/Activity.php
<?php

namespace App;

use App\BaseModel as Model;

class Activity extends Model
{
    protected $fillable = [
        "department_id",
        "title",
        "description",
        "is_event",
        "is_program",
    ];

    // protected $guarded = [];

    public function logs()
    {
        return $this->hasMany('\App\ActivityLog');
    }

    public function department()
    {
        return $this->belongsTo('\App\Department');
    }
}

app/Http/Controllers/ActivitiesController.php
<?php

namespace App\Http\Controllers;

use App\Activity;
use App\Institute;
use App\Department;

use Illuminate\Http\Request;
use App\Dependencies\CustomBuilder;

use DB;

class ActivitiesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(CustomBuilder $builder)
    {
        $html = $builder
            ->parameters()
            ->ajax([
                'url' => route('datatables.activities'),
            ])
            ->columns([
                ['data' => 'title',             'title' => trans('datatables.header.title')],
                ['data' => 'department.title',     'title' => trans('datatables.header.department')],
            ])
            ->addAction();
        return view('activities.index')->with(compact('html'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $institutes = Institute::all()->pluck('fulltitle', 'id');

        $institutes->prepend('Please Choose Institutes', '');

        return view('activities.form')->with([
            'institutes' => $institutes
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $activity = DB::transaction(function () use ($request) {
            $activity = new Activity($request->all());
            $activity->department_id = $request->input('department.id');
            $activity->save();
            return $activity;
        });
        return redirect()->route('activities.show', $activity->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Activity  $activity
     * @return \Illuminate\Http\Response
     */
    public function show(Activity $activity)
    {
        return view('activities.show')->with([
            'activity' => $activity,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Activity  $activity
     * @return \Illuminate\Http\Response
     */
    public function edit(Activity $activity)
    {
        $institutes = Institute::all()->pluck('fulltitle', 'id');
        $departments = Department::all()->pluck('title', 'id');

        $institutes->prepend('Please Choose Institutes', '');
        $departments->prepend('Please Choose Institutes', '');

        return view('activities.form')->with([
            'activity' => $activity,
            'institutes' => $institutes,
            'departments' => $departments,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Activity  $activity
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Activity $activity)
    {
        $activity = DB::transaction(function () use ($activity, $request) {
            $activity->update($request->all());
            return $activity;
        });
        return redirect()->route('activities.show', $activity->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Activity  $activity
     * @return \Illuminate\Http\Response
     */
    public function destroy(Activity $activity)
    {
        DB::transaction(function () use ($activity) {
            $activity->delete();
        });
        return redirect()->back();
    }
}

resources/views/activities/form.blade.php
@extends('layouts.dashboard')

@section('css')
{!! Layouts::usePlugin('select2', 'css') !!}
@endsection

@section('breadcrumbs')
{!! Layouts::breadcrumbs(['type' => $isEdit ? 'edit' : 'create', 'module' => $isEdit ? $activity : null, 'route' => 'activities'], true) !!}
@endsection

@section('content')
<section class="content">
    <h4>{{ $isEdit ? "EDIT" : "CREATE NEW" }} ACTIVITY</h4>
    <div class="row">
        <div class="col-xs-12">
            @if ($isEdit)
                {!! Form::model($activity, ['route' => ['activities.update', $activity->id], 'method' => 'put']) !!}
                {!! Form::hidden('isEdit', true) !!}
            @else
                {!! Form::open(['route' => ['activities.store'], 'method' => 'post']) !!}
            @endif
            <div class=x_panel>
                <div class=x_title>
                    <strong>Activity Properties</strong>
                    <small>Form</small>
                </div>
                <div class=x_content>
                    <div class="row">
                        <div class="col-xs-12">
                            @if (! $isEdit)
                                <div class="form-group">
                                    {!! Form::label('', 'Institute', ['class' => 'form-label']) !!}
                                    {!! Form::select('institute[id]', $institutes, null, ['class' => 'form-control select2' , 'data-department-url' => route('departments.index')]) !!}
                                    @if ($isEdit)
                                        {!! Form::hidden('institute[id]', $activity->department->institute->id) !!}
                                    @endif
                                </div>
                            @endif
                            <div class="form-group">
                                {!! Form::label('', 'Department', ['class' => 'form-label']) !!}
                                {!! Form::select('department[id]', $isEdit ? $departments : [], null, ['class' => 'form-control select2', 'disabled']) !!}
                                @if ($isEdit)
                                    {!! Form::hidden('department[id]', $activity->department->id) !!}
                                @endif
                            </div>
                            <div class="form-group form-float">
                                {!! Form::label('', 'Activity title', ['class' => 'form-label']) !!}
                                {!! Form::text('title', null, ['class' => 'form-control', 'placeholder' => 'Describe activity title']) !!}
                            </div>
                            <div class="form-group form-float">
                                {!! Form::label('', "Activity description", ['class' => 'form-label']) !!}
                                {!! Form::textarea('description', null, ['class' => 'form-control', 'placeholder' => 'Describe activity description in longer text']) !!}
                            </div>
                            <div class="form-check">
                                <label class="form-check-label">
                                    {!! Form::hidden('is_event', 0) !!}
                                    {!! Form::checkbox('is_event', true, null, ['class' => 'form-check-input']) !!}
                                    &nbsp;Is Event
                                </label>
                            </div>
{{--                             <div class="form-check">
                                <label class="form-check-label">
                                    {!! Form::hidden('locked', 0) !!}
                                    {!! Form::checkbox('locked', true, null, ['class' => 'form-check-input']) !!}
                                    &nbsp;Is Programs
                                </label>
                            </div> --}}
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-dot-circle-o"></i> Submit</button>
                    <button type="reset" class="btn btn-sm btn-danger"><i class="fa fa-ban"></i> Reset</button>
                </div>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
</section>
@endsection

@push('js')
{!! Layouts::usePlugin('select2', 'js') !!}
{{-- {!! Layouts::usePlugin('parsley', 'js') !!} --}}
<script type="text/javascript">
    $(document).ready(function() {
        $('select[name="institute[id]"]').change(function() {
            url = $(this).data('department-url');
            institute_id = $(this).val();
            data = {
                'institute_id': institute_id,
                'action': 'institutes_dropdown'
            }
            $.get(url, data, function(data, textStatus, xhr) {
                selectDept = $('select[name="department[id]"]');
                selectDept.empty();
                $.each(data, function(id, title) {
                    selectDept.append($("<option></option>")
                       .attr("value", id).text(title));
                });
                selectDept.removeAttr('disabled');
                selectDept.select2();
            });
        });
    });
</script>
@endpush

resources/views/activities/index.blade.php
@extends('layouts.dashboard')

@section('css')
    {!! Layouts::usePlugin('datatables', 'css') !!}
@endsection

@section('content')
    @component('layouts.components.datatables')
        @slot('title')
            @choice('activities.title', 2)
        @endslot

        @slot('topButton')
            @can('create', 'App\User')
                <a href="{{ route('activities.create') }}" class="btn btn-primary btn-sm pull-right">
                    <i class="fa fa-fw fa-user"></i> New @choice('activities.title', 1)
                </a>
            @endcan
        @endslot

        @slot('table')
            {!! $html->table(['style' => 'width:100%;']) !!}
        @endslot

    @endcomponent
@endsection

@push('js')
    {!! Layouts::usePlugin('datatables', 'js') !!}
    {!! $html->scripts() !!}
@endpush

resources/views/activities/show.blade.php
@extends('layouts.dashboard')

@section('css')
@endsection

@section('breadcrumbs')
    {{-- <li class="breadcrumb-item"><a href="{{ route('institutes.index') }}">Institute</a></li> --}}
    {{-- <li class="breadcrumb-item"><a href="{{ route('institutes.show', $institute->id) }}">{{ getInitials($institute->title)." ".$institute->name }}</a></li> --}}
@endsection

@section('content')
<section class="content">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Activity Detail <small> {{ $activity->title }}</small></h3>
            </div>

            {{-- <div class="title_right"> --}}
                {{-- <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search"> --}}
                    {{-- <div class="input-group"> --}}
                        {{-- <input type="text" class="form-control" placeholder="Search for..."> --}}
                        {{-- <span class="input-group-btn"> --}}
                            {{-- <button class="btn btn-default" type="button">Go!</button> --}}
                        {{-- </span> --}}
                    {{-- </div> --}}
                {{-- </div> --}}
            {{-- </div> --}}
        </div>

        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Overview</h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            {{-- <li class="dropdown"> --}}
                                {{-- <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a> --}}
                                {{-- <ul class="dropdown-menu" role="menu"> --}}
                                    {{-- <li><a href="#">Settings 1</a> --}}
                                    {{-- </li> --}}
                                    {{-- <li><a href="#">Settings 2</a> --}}
                                    {{-- </li> --}}
                                {{-- </ul> --}}
                            {{-- </li> --}}
                            {{-- <li><a class="close-link"><i class="fa fa-close"></i></a> --}}
                            {{-- </li> --}}
                        </ul>
                        <div class="clearfix"></div>
                    </div>

                    <div class="x_content">

                        <div class="col-md-9 col-sm-9 col-xs-12">

                            <ul class="stats-overview">
                                <li>
                                    <span class="name"> Estimated budget </span>
                                    <span class="value text-success"> 2300 </span>
                                </li>
                                <li>
                                    <span class="name"> Total amount spent </span>
                                    <span class="value text-success"> 2000 </span>
                                </li>
                                <li class="hidden-phone">
                                    <span class="name"> Estimated project duration </span>
                                    <span class="value text-success"> 20 </span>
                                </li>
                            </ul>
                            <br />

                            <div id="mainb" style="height:350px;"></div>

                            <div>

                                <h4>Recent Activity
                                    <span class="pull-right"><button data-method="POST" data-url="{{ route('activitylogs.store') }}" data-title="" data-date="{{ \Carbon\Carbon::now()->format('Y-m-d') }}" class="btn btn-xs btn-success activitylog-edit" style="margin-right: 0"><i class="fa fa-plus"></i> Add</button></span>
                                </h4>
                                <!-- end of user messages -->
                                <ul class="messages">
                                    @foreach ($activity->logs as $log)
                                    <li>
                                        <img src="{{ asset('images/img.jpg') }}" class="avatar" alt="Avatar">
                                        <div class="message_date">
                                            {!! Form::open([ 'url' => route('activitylogs.destroy', $log->id), 'method'=>'delete', 'class'=>'form-inline','style="display:inline;"' ]) !!}
                                            <div class="btn-group">
                                                <button data-method="PUT" data-url="{{ route('activitylogs.update', $log->id) }}" data-title="{{ $log->title }}" data-date="{{ $log->date->format('Y-m-d') }}" class="activitylog-edit btn btn-xs btn-warning" data-toggle="tooltip" data-placement="bottom" title="Edit"><i class="fa fa-pencil"></i></button>
                                                <button href="#" data-confirm="Are you sure to delete this resources?" class="btn btn-danger btn-xs js-delete-confirm" data-toggle="tooltip" data-placement="bottom" title="Delete">
                                                    <i class="fa fa-trash-o"></i>
                                                </button>
                                            </div>
                                            {!! Form::close() !!}
                                            <h3 class="date text-info">{{ $log->date->format('d') }}</h3>
                                            <p class="month">{{ $log->date->format('M') }}</p>
                                        </div>
                                        <div class="message_wrapper">
                                            <h4 class="heading">{{ $log->user->email }}</h4>
                                            <blockquote class="message">{{ $log->title }}</blockquote>
                                            <br />
                                            <p class="url">
                                                <span class="fs1 text-info" aria-hidden="true" data-icon=""></span>
                                                <a href="#"><i class="fa fa-paperclip"></i> User Acceptance Test.doc </a>
                                            </p>
                                        </div>
                                    </li>
                                    @endforeach
                                </ul>
                                <!-- end of user messages -->


                            </div>


                        </div>

                        <!-- start project-detail sidebar -->
                        <div class="col-md-3 col-sm-3 col-xs-12">
                            <section class="panel">
                                <div class="x_title">
                                    <h2>Activity Description</h2>
                                    <div class="clearfix"></div>
                                </div>
                                <div class="panel-body">
                                    <h3 class="green"><i class="fa fa-bolt"></i> {{ $activity->title }}</h3>

                                    <p>{{ $activity->description }}</p>
                                    <br />

                                    <div class="project_detail">
                                        <p class="title"><i class="fa fa-sitemap"></i> Institute</p>
                                        <p>{{ $activity->department->institute->full_title }} <a href="{{ route('institutes.show', $activity->department->institute->id) }}"><i class="fa fa-external-link"></i></a></p>
                                        <p class="title"><i class="fa fa-sitemap"></i> Department</p>
                                        <p>{{ $activity->department->title }} <a href="{{ route('departments.show', $activity->department->id) }}"><i class="fa fa-external-link"></i></a></p>
                                    </div>

                                    <br />
{{--                                     <h5>Project files</h5>
                                    <ul class="list-unstyled project_files">
                                        <li><a href=""><i class="fa fa-file-word-o"></i> Functional-requirements.docx</a>
                                        </li>
                                        <li><a href=""><i class="fa fa-file-pdf-o"></i> UAT.pdf</a>
                                        </li>
                                        <li><a href=""><i class="fa fa-mail-forward"></i> Email-from-flatbal.mln</a>
                                        </li>
                                        <li><a href=""><i class="fa fa-picture-o"></i> Logo.png</a>
                                        </li>
                                        <li><a href=""><i class="fa fa-file-word-o"></i> Contract-10_12_2014.docx</a>
                                        </li>
                                    </ul>
                                    <br />

                                    <div class="text-center mtop20">
                                        <a href="#" class="btn btn-sm btn-primary">Add files</a>
                                        <a href="#" class="btn btn-sm btn-warning">Report contact</a>
                                    </div> --}}
                                </div>

                            </section>

                        </div>
                        <!-- end project-detail sidebar -->

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<div id="modal-activitylog" class="modal center fade" tabindex="-1" role="dialog" aria-labelledby="modal-activitylog" aria-hidden="true" style="display: none;">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-body">
                <div style="padding: 5px 20px;">
                    {!! Form::open(['id' => 'form-activitylog', 'class' => 'form-horizontal']) !!}
                        {!! Form::hidden('activity.id', $activity->id) !!}
                        {!! Form::hidden('user.id', auth()->id()) !!}
                        {{ method_field('POST') }}
                        <div class="form-group">
                            {!! Form::label('title', 'Log', ['class' => 'col-sm-1 control-label']) !!}
                            <div class="col-sm-3">
                                {!! Form::date('date', \Carbon\Carbon::now(), ['class' => 'form-control']) !!}
                            </div>
                            <div class="col-sm-6">
                                {!! Form::text('title', null, ['class' => 'form-control']) !!}
                            </div>
                            <div class="col-sm-2">
                                <button type="submit" class="pull-right btn btn-success"><i class="fa fa-check"></i></button>
                                <button type="button" class="pull-right btn btn-danger" data-dismiss="modal"><i class="fa fa-close"></i></button>
                            </div>
                        </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('js')
<script type="text/javascript">
    $('#modal-activitylog').on('shown.bs.modal', function(event) {
        $('input[name="title"]').focus();
    });
    $(".activitylog-edit").click(function(event) {
        event.preventDefault();
        var
            date = $(this).data('date');
            title = $(this).data('title');
            url = $(this).data('url');
            method = $(this).data('method');

            console.log(date);
            console.log(title);

        $('#form-activitylog').attr({
            action: url,
        });;

        $('#form-activitylog').find('input[name="date"]').val(date);
        $('#form-activitylog').find('input[name="title"]').val(title);
        $('#form-activitylog').find('input[name="_method"]').val(method);

        $('#modal-activitylog').modal('show');
    });
</script>
@endpush